apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_CACHE@microservice-auth-cache-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-data
    version: 1.70.1-auth-config-info
spec:
  clusterIP: None
  ports:
    -
      port: '${INTERNAL_PORT_CACHE@microservice-auth-cache-config}'
      targetPort: '${INTERNAL_PORT_CACHE@microservice-auth-cache-config}'
  selector:
    app: '${STATEFUL_CACHE@microservice-auth-cache-config}'
