apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE@microservice-auth-cache-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-cache
    version: 1.70.0-data-cache-version-prod
spec:
  clusterIP: None
  ports:
    -
      port: '${INTERNAL_PORT@microservice-auth-cache-config}'
      targetPort: '${INTERNAL_PORT@microservice-auth-cache-config}'
  selector:
    app: '${STATEFUL@microservice-auth-cache-config}'
