apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '${STATEFUL@microservice-auth-cache-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-cache
    version: 1.70.0-data-cache-version-prod
spec:
  serviceName: '${SERVICE@microservice-auth-cache-config}'
  selector:
    matchLabels:
      app: '${STATEFUL@microservice-auth-cache-config}'
  replicas: 1
  template:
    metadata:
      labels:
        moduleid: microservice-auth-cache
        version: 1.70.0-data-cache-version-prod
        app: '${STATEFUL@microservice-auth-cache-config}'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        -
          name: data
          image: 'redis:3.2-alpine'
          args:
            - '--requirepass'
            - SECRET_PASSWORD_CACHE
            - '--appendonly'
            - yes
            - '--save'
            - '900'
            - '1'
            - '--save'
            - '30'
            - '1'
          ports:
            -
              containerPort: '${INTERNAL_PORT@microservice-auth-cache-config}'
          volumeMounts:
            -
              name: microservice-auth-cache-storage
              mountPath: /data
  volumeClaimTemplates:
    -
      metadata:
        name: microservice-auth-cache-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi
